language: python

python:
  - 3.5
  - 3.6

services: postgresql

env:
  global:
  - DJANGO=1.11

before_install:
  - DJANGO_SETTINGS_MODULE=your_project.settings
  - PYTHONPATH=$HOME/builds/travis/build/Sidon/work-at-olist.git
  - PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python manage.py migrate --noinput
  
  
