language: python
python:
- 3.6

services: postgresql
dist: trusty

env:
  global:
  - DJANGO=1.11

before_install:
- DJANGO_SETTINGS_MODULE=workatolist.settings
- PYTHONPATH=$HOME/builds/travis/build/Sidon/work-at-olist.git
- PIP_USE_MIRRORS=true

install:
- pip install -r requirements.txt
- pip install psycopg2 --quiet
- pip install Crypto
- pip install pycrypto  

before_script:
- psql -c "CREATE DATABASE travisci;" -U postgres

script:
- python manage.py migrate --noinput

# Tests
- python manage.py test

